### ISSUE TITLE
start方法在哪儿定义的?

### ISSUE THREAD

**Issue by phyer** [fex-team/alogs#3]
文档中有描述:
moduleTracker.start(fields) 同步方法(Sync)
alog('module.start', fields) 异步方法(Async)

这里面的start 是Tracker的方法吗?alogs.js的代码里没有发现?

**Comment by zswang** [comment]
请使用 `create` 方法，之前改过名，没有更新文档。

**Comment by zswang** [comment]
文档已经更新，感谢反馈
