### ISSUE TITLE
entry函数绑定 entry.on = on,entry.tracker = getTracker等类似函数的设计和效率问题。

### ISSUE THREAD

**Issue by zhangleigang** [fex-team/alogs#5]
1.函数嵌套函数是一种不推荐的方式吧？
http://js8.in/2011/10/19/javascript%E5%B5%8C%E5%A5%97%E5%87%BD%E6%95%B0%E7%9A%84%E6%95%88%E7%8E%87%E9%97%AE%E9%A2%98/
2.为什么不绑在entry的原型对象上？
例如entry.prototype.on = on

**Comment by zswang** [comment]
`entery` 也就是 alog.js 加载后 `alog` 实例（是一个函数）
一个页面里只会出现一个 `alog` 实例，类似 `jQuery` 的 `$`
不需要构建出来，也就没有必要使用 `prototype`

**Comment by zhangleigang** [comment]
感谢回答！一个页面里只会出现一个 alog 实例对我阅读源码有很大的帮助，不知道是否有进一步开源的打算，保持开源alog和线上跑的代码版本一致。因为我看到该项目很少更新了，我理解的是alog就像总的一个上报module的管理，更核心的是类似speed.js，monkey.js子模块，子模块因为每个公司业务和关注点不同有所差异。
