### ISSUE TITLE
请教个apply使用问题

### ISSUE THREAD

**Issue by jason1ee** [fex-team/alogs#7]
entry.p = entry.q = { // 接管之前的定义
            push: function (args) {
                entry.apply(entry, args);
            }
        };
        // 开始处理缓存命令
        for (var i = 0; i < items.length; i++) {
            entry.apply(entry, items[i]);
        }

上面的代码中entry.apply(entry, args);不是等同于entry(args);吗？为什么要通过apply方法调用呢

**Comment by zswang** [comment]
> 为什么要通过 apply 方法调用呢

在 alogs 没有加载之前调用 `alog(a, b, c, d)` 会将调用参数缓存，类似：`q.push([a, b, c, d])`

```
function(){(e[o].q=e[o].q||[]).push(arguments)}
```

当 alogs 加载完毕后，才处理缓存，由于缓存的是 `arguments` 类是一个数组类型。
所以得用 apply 处理。

等价于：`entry(args[0], args[1], args[2]....);`

参考：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Function/apply

**Comment by jason1ee** [comment]
懂了。忘了参数问题了。十分感谢！
